### ISSUE TITLE
./tools/run_face_detection_on_fddb.py fails

### ISSUE THREAD

**Issue by emely-pi** [playerkk/face-py-faster-rcnn#11]
Hi,
when I try to run "python ./tools/run_face_detection_on_fddb.py" I get this error:

Loaded network output/faster_rcnn_end2end/train/vgg16_faster_rcnn_iter_80000.caffemodel
1 Traceback (most recent call last):
  File "./tools/run_face_detection_on_fddb.py", line 146, in <module>
    scores, boxes = im_detect(net, im)
  File "/home/emely/face-py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 121, in im_detect
    blobs, im_scales = _get_blobs(im, boxes)
  File "/home/emely/face-py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 103, in _get_blobs
    blobs['data'], im_scale_factors = _get_image_blob(im)
  File "/home/emely/face-py-faster-rcnn/tools/../lib/fast_rcnn/test.py", line 33, in _get_image_blob
    im_orig = im.astype(np.float32, copy=True)
AttributeError: 'NoneType' object has no attribute 'astype'

Can anbody help me?

**Comment by Tommy-Jumper** [comment]
Endlich :-) Hi Emely, du wirst dich wahrscheinlich nicht mehr an mich erinnern, wir haben uns im Flug von Shanghai nach Moskau kennengelernt und uns dann noch auf dem Flughafen etwas unterhalten. Leider hat es mit der Kontaktaufnahme via Facebook nicht wirklich geklappt und somit versuche ich hier mal mein Glück. Ach ja, Thomas hier und wenn es bei dir jetzt ggf. Klick gemacht hat, dann würde ich sehr gern auf das Angebot der Currywurst zurückkommen und würde mich sehr freuen, wenn du dich bei mir meldest. Viel mehr möchte ich hier auch nicht schreiben und hoffe sehr, das du das irgendwann mal liest und mich kontaktierst. LG und vielleicht auf bald

Thomas
