### ISSUE TITLE
Also about Evaluation

### ISSUE THREAD

**Issue by ShiningCoding** [playerkk/face-py-faster-rcnn#12]
Hi, @playerkk . Thank you for your wonderful shared code! Now I have trained a model using data WIDER, but when I run your code for test_net, the problem of "global name 'datasets' is not defined" confused me, which points at the 412th line in file "/lib/datasets/face.py". Can you tell me how to deal with it?
Additionally, how is the accuracy calculated in the training process? 
Thank you very much!

**Comment by staceycy** [comment]
@ShiningCoding hi, I have met the same problem. 
Have you solved it?
Thank you.

**Comment by playerkk** [comment]
Can you try 
```console
export PYTHONPATH=./lib:$PYTHONPATH
```
under the root directory of the code?
