### ISSUE TITLE
cannot download train annotation file for wider face dataset

### ISSUE THREAD

**Issue by moonhoenlee** [playerkk/face-py-faster-rcnn#16]
The annotation file(http://jianghz.me/files/wider_face_train_annot.txt) mentioned in the readme does not open. How can I get the file?

**Comment by flrngel** [comment]
https://people.cs.umass.edu/~hzjiang//files/wider_face_train_annot.txt

you're welcome

**Comment by moonhoenlee** [comment]
Thanks :)
