### ISSUE TITLE
Train my own data and get the Assertionerror

### ISSUE THREAD

**Issue by ManningZhang** [playerkk/face-py-faster-rcnn#17]
Hi playerkk
I follow your instructions to train the face detection and I successed. Now I'm trying to train my own data based on your work, I cancelled the cache and output dirs, and make my own data as same as wider face you used before. But when I but when i run the command:"./experiments/scripts/faster_rcnn_end2end.sh 0 VGG16 wider",I got the errors as follows:
`+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ GPU_ID=0
+ NET=VGG16
+ NET_lc=vgg16
+ DATASET=wider
+ array=($@)
+ len=3
+ EXTRA_ARGS=
+ EXTRA_ARGS_SLUG=
+ case $DATASET in
+ TRAIN_IMDB=wider_train
+ TEST_IMDB=wider_test
+ PT_DIR=face
+ ITERS=80000
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/faster_rcnn_end2end_VGG16_.txt.2017-10-26_15-01-22
+ exec
++ tee -a experiments/logs/faster_rcnn_end2end_VGG16_.txt.2017-10-26_15-01-22
+ echo Logging output to experiments/logs/faster_rcnn_end2end_VGG16_.txt.2017-10-26_15-01-22
Logging output to experiments/logs/faster_rcnn_end2end_VGG16_.txt.2017-10-26_15-01-22
+ ./tools/train_net.py --gpu 0 --solver models/face/VGG16/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/VGG16.v2.caffemodel --imdb wider_train --iters 80000 --cfg experiments/cfgs/faster_rcnn_end2end.yml
Called with args:
Namespace(cfg_file='experiments/cfgs/faster_rcnn_end2end.yml', gpu_id=0, imdb_name='wider_train', max_iters=80000, pretrained_model='data/imagenet_models/VGG16.v2.caffemodel', randomize=False, set_cfgs=None, solver='models/face/VGG16/faster_rcnn_end2end/solver.prototxt')
Using config:
{'DATA_DIR': '/home/manning/FRCN_MONKEY_NEW/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'faster_rcnn_end2end',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/manning/FRCN_MONKEY_NEW/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/manning/FRCN_MONKEY_NEW',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 3,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 64,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': -0.1,
           'FG_FRACTION': 0.4,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1024,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 3,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [1024],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 5000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
Traceback (most recent call last):
  File "./tools/train_net.py", line 106, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 71, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 64, in get_roidb
    imdb = get_imdb(imdb_name)
  File "/home/manning/FRCN_MONKEY_NEW/tools/../lib/datasets/factory.py", line 52, in get_imdb
    return __sets[name]()
  File "/home/manning/FRCN_MONKEY_NEW/tools/../lib/datasets/factory.py", line 40, in <lambda>
    __sets[name] = (lambda split=split: face(split, 0, wider_devkit_path))
  File "/home/manning/FRCN_MONKEY_NEW/tools/../lib/datasets/face.py", line 47, in __init__
    self._image_index, self._gt_roidb = self._load_image_set_index()
  File "/home/manning/FRCN_MONKEY_NEW/tools/../lib/datasets/face.py", line 114, in _load_image_set_index
    assert(image_ext == '.png' or image_ext == '.jpg' or image_ext == '.jpeg')
AssertionError`
Can you help me to fix the problem? Thanks~

**Comment by playerkk** [comment]
It is assumed the format of training images is either png or jpg. So I simply check the suffix of an image name to be one of "png", "jpg", or "jpeg".

**Comment by delian11** [comment]
hello,I've met the same problem.Did you solve the problem and how?Thanx

**Comment by Hans1984** [comment]
you need to check text coding method, and print the suffix may help.
