### ISSUE TITLE
about the wider face data

### ISSUE THREAD

**Issue by Usernamezhx** [playerkk/face-py-faster-rcnn#2]
hi 
    I follow your guide to start this project. I download the data WIDER face.but when i run the command:"No dataset given" , i find that the faster_rcnn_end2end.sh scripts only support only voc and coco data. and then i try to convert the wider face data to the voc style . but i meet a new question:assert (boxes[:, 2] >= boxes[:, 0]).all() .i try all i can do ,but it does not work.

**Comment by playerkk** [comment]
The faster_rcnn_end2end.sh script does support the wider dataset. You might need to exactly follow the instructions in the readme file.

**Comment by Usernamezhx** [comment]
hi playerkk
      I am a fresh bird,you said the faster_rcnn_end2end.sh script does support the wider dataset,but i open the faster_rcnn_end2end.sh. it said that :
    case $DATASET in
    pascal_voc)
    TRAIN_IMDB="voc_2007_trainval"
    TEST_IMDB="voc_2007_test"
    PT_DIR="pascal_voc"
    ITERS=70000
    ;;
  coco)
    # This is a very long and slow training schedule
    # You can probably use fewer iterations and reduce the
    # time to the LR drop (set in the solver to 350,000 iterations).
    TRAIN_IMDB="coco_2014_train"
    TEST_IMDB="coco_2014_minival"
    PT_DIR="coco"
    ITERS=490000
    ;;
  *)
    echo "No dataset given"
    exit
    ;;
esac
i have no idea .i need your help,thank you

**Comment by playerkk** [comment]
Are you talking about this file? https://github.com/playerkk/face-py-faster-rcnn/blob/master/experiments/scripts/faster_rcnn_end2end.sh

**Comment by Usernamezhx** [comment]
oh my god ......i use the rbgirshick faster rcnn  faster_rcnn_end2end.sh......many many many thanks.......

**Comment by Usernamezhx** [comment]
is there anything i should replace? thank you very much.

**Comment by Usernamezhx** [comment]
i clone your project . thank you very much........ : )

**Comment by Usernamezhx** [comment]
hi playerkk
    I am sorry to bother you .I think i should run it first and then to analysis it.
    AssertionError: Path does not exist: data/WIDER/train_face_train_annot.txt .
  i think it has some problem with the file name .

image_set_file = self._name + '_face_' + self._image_set + '_annot.txt'
I think it should not produce the name :train_face_train_annot.txt 

   I input the command:　**voole@zhx:~/face-py-faster-rcnn$ ./experiments/scripts/faster_rcnn_end2end.sh 0 ZF wider **

thanks for your help
                                                                                                                                          zhanghongxing

**Comment by Usernamezhx** [comment]
i really really really really really need your help, if you dont have time ,i will be waiting for you.

**Comment by playerkk** [comment]
I would strongly recommend you to read the instructions before running the cod. https://github.com/playerkk/face-py-faster-rcnn/blob/master/README.md

**Comment by Usernamezhx** [comment]
I am sorry to bother you again ,I have read the README for several times , http://blog.csdn.net/zhanghongxing007/article/details/56479206    
I write down the details, I hope you can read for several minutes, thanks for your help.

**Comment by playerkk** [comment]
You didn't do the step 4 of the section "prepare the training data".

**Comment by Usernamezhx** [comment]
first of all . thank you very much. that i use the folder WIDER/WIDER_train/ to Create symlinks. after that , it said that need:  
AssertionError: Selective search data not found at: /home/voole/face-py-faster-rcnn/data/WIDER/train.mat
so i down the wider_face_split.zip from the WIDER FACE NET. and then i change the name wider_face_train.mat to train.mat
after that i meet a new problem:
NotImplementedError: Please use HDF reader for matlab v7.3 files
so i have to change the scipy  io to fit the v7.3 but................i cant find the loadmat function............

**Comment by playerkk** [comment]
I tested the repository on another machine. I also had some errors of loading wider dataset. But different from yours. I've updated the source files. Please update the repository by doing "git pull origin master" and re-run the program as "./experiments/scripts/faster_rcnn_end2end.sh 0 VGG16 wider"

Sorry for the inconvenience.

**Comment by Usernamezhx** [comment]
hi playerkk
First of all ,thanks for your reply.  I am sorry to bother you again again again....but i have be here for one day.
`Traceback (most recent call last):
  File "./tools/train_net.py", line 106, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 71, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 68, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/voole/face-py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 118, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/voole/face-py-faster-rcnn/tools/../lib/datasets/imdb.py", line 106, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/voole/face-py-faster-rcnn/tools/../lib/datasets/imdb.py", line 67, in roidb
    self._roidb = self.roidb_handler()
  File "/home/voole/face-py-faster-rcnn/tools/../lib/datasets/face.py", line 227, in selective_search_roidb
    ss_roidb = self._load_selective_search_roidb(gt_roidb)
  File "/home/voole/face-py-faster-rcnn/tools/../lib/datasets/face.py", line 247, in _load_selective_search_roidb
    'Selective search data not found at: {}'.format(filename)
AssertionError: Selective search data not found at: /home/voole/face-py-faster-rcnn/data/WIDER/wider.mat
`
wider.mat? it means the wider_face_train.mat?
Look forward to your reply

**Comment by playerkk** [comment]
It's weird. Since we are using RPN to generate proposals, there is no need to call the _load_selective_search_roidb function. Can you post your command to run the code?

**Comment by Usernamezhx** [comment]
hi playerkk
       thanks for your reply. i  write down the detail at the : http://blog.csdn.net/zhanghongxing007/article/details/56479206
many thanks.

**Comment by playerkk** [comment]
Sorry, I should have mentioned only VGG16 is currently supported.

**Comment by Usernamezhx** [comment]
Hi playerkk
    yeah,i use the command:./experiments/scripts/faster_rcnn_end2end.sh 0 VGG16 wider. i use the VGG16 net.

**Comment by Usernamezhx** [comment]
i have the same quetion .the faster rcnn use the RPN net instead of the selective_search. I  called some old script for fast-rcnn ?

**Comment by playerkk** [comment]
You are training a faster r-cnn. Do you have errors right now?

**Comment by Usernamezhx** [comment]
when i input the conmmand:  './experiments/scripts/faster_rcnn_end2end.sh 0 VGG16 wider'
it still point that : ' Selective search data not found at: /home/voole/face-py-faster-rcnn/data/WIDER/wider.mat'
i am sorry to bother you.

**Comment by playerkk** [comment]
It seems case sensitive. Try vgg16 instead of VGG16. Also do "git pull origin master" to update the source files.

**Comment by playerkk** [comment]
You might also need to delete *.pkl files in the cache folder.

**Comment by Usernamezhx** [comment]
hi man
    i have solved this question~~~,because of the easydict, my version is 1.4 .even i config the yml. but easydict did not pass the parameter to the train_net.py. so ...... the solution is to update your easydict. thank you very much very much very much
