### ISSUE TITLE
Replace VGG16 with a series of ResNet   

### ISSUE THREAD

**Issue by xiezheng-cs** [playerkk/face-py-faster-rcnn#23]
Hi, everyone! I can't find the Caffe version of resnet34 that was pre trained on Imagenet, and the other resnet has been successfully replaced.
![controc-compare](https://user-images.githubusercontent.com/33676557/38991636-f3f50532-4410-11e8-9d26-2f23f0979de8.png)

**Comment by xiezheng-cs** [comment]
Anyone can help me?

**Comment by playerkk** [comment]
Sorry for the late response.

You might want to try ResNet50 or ResNet101 in Caffe format.
