### ISSUE TITLE
Could not understand the result

### ISSUE THREAD

**Issue by annw0922** [playerkk/face-py-faster-rcnn#24]
after I run the python ./tools/run_face_detection_on_fddb.py --gpu=0 to test the model

the output is like
1 3.448 6.897 10.345 13.793 17.241 20.690 24.138 27.586 31.034 34.483 37.931 41.379 44.828 48.276 51.724 55.172 58.621 62.069 65.517 68.966 72.414 75.862 79.310 82.759 86.207 89.655 93.103 96.552 100.000 
2 3.509 7.018 10.526 14.035 17.544 21.053 24.561 28.070 31.579 35.088 38.596 42.105 45.614 49.123 52.632 56.140 59.649 63.158 66.667 70.175 73.684 77.193 80.702 84.211 87.719 91.228 94.737 98.246 
3 3.650 7.299 10.949 14.599 18.248 21.898 25.547 29.197 32.847 36.496 40.146 43.796 47.445 51.095 54.745 58.394 62.044 65.693 69.343 72.993 76.642 80.292 83.942 87.591 91.241 94.891 98.540 
4 3.311 6.623 9.934 13.245 16.556 19.868 23.179 26.490 29.801 33.113 36.424 39.735 43.046 46.358 49.669 52.980 56.291 59.603 62.914 66.225 69.536 72.848 76.159 79.470 82.781 86.093 89.404 92.715 96.026 99.338 
5 3.356 6.711 10.067 13.423 16.779 20.134 23.490 26.846 30.201 33.557 36.913 40.268 43.624 46.980 50.336 53.691 57.047 60.403 63.758 67.114 70.470 73.826 77.181 80.537 83.893 87.248 90.604 93.960 97.315 
6 3.311 6.623 9.934 13.245 16.556 19.868 23.179 26.490 29.801 33.113 36.424 39.735 43.046 46.358 49.669 52.980 56.291 59.603 62.914 66.225 69.536 72.848 76.159 79.470 82.781 86.093 89.404 92.715 96.026 99.338 
7 3.584 7.168 10.753 14.337 17.921 21.505 25.090 28.674 32.258 35.842 39.427 43.011 46.595 50.179 53.763 57.348 60.932 64.516 68.100 71.685 75.269 78.853 82.437 86.022 89.606 93.190 96.774 
8 3.623 7.246 10.870 14.493 18.116 21.739 25.362 28.986 32.609 36.232 39.855 43.478 47.101 50.725 54.348 57.971 61.594 65.217 68.841 72.464 76.087 79.710 83.333 86.957 90.580 94.203 97.826 
9 3.861 7.722 11.583 15.444 19.305 23.166 27.027 30.888 34.749 38.610 42.471 46.332 50.193 54.054 57.915 61.776 65.637 69.498 73.359 77.220 81.081 84.942 88.803 92.664 96.525 
10 3.571 7.143 10.714 14.286 17.857 21.429 25.000 28.571 32.143 35.714 39.286 42.857 46.429 50.000 53.571 57.143 60.714 64.286 67.857 71.429 75.000 78.571 82.143 85.714 89.286 92.857 96.429 100.000 

But I can not understand it and I didn't find some information about it in readme...excuse me for being stupid but could anyone help me with understanding it?

**Comment by playerkk** [comment]
The first number indicates which fold (10 folds in total). Other numbers are simply percentages of finished images in a particular fold.
