### ISSUE TITLE
about WIDER/FDDB

### ISSUE THREAD

**Issue by foralliance** [playerkk/face-py-faster-rcnn#30]
@playerkk　HI

有2个问题想请教：
1. 
在使用wider数据集训练时，发现您对标签数据进行了简单修改．即，没有使用官方提供的`wider_face_train_bbx_gt.txt`，而是自己定义了一个`wider_face_train_annot.txt`．
这么做的原因是什么呢？？

2. 
FDDB数据集测试时，您得到的结果形式是：
`191.090973 67.139038 156.147095 207.192780 0.999`891
对应的是**rectangle box**
但实际标签中是**ellipse box**，形式为：
`123.583300 85.549500 1.265839 269.693400 161.781200  1`

在FDDB数据进行检测时，需要的也是**ellipse box**．请问您是如何将检测结果中的rectangle box转为ellipse box的？？

麻烦了！！

**Comment by playerkk** [comment]
Sorry for the late response.

1. I personally found parsing a txt file is much easier than mat files in Python.

2. FDDB supports rectangles as input for evaluation. I didn't convert results to ellipses.

**Comment by foralliance** [comment]
@playerkk  HI
感谢您的回复！
