### ISSUE TITLE
Can't clone your repository

### ISSUE THREAD

**Issue by SergeyMalashenko** [playerkk/face-py-faster-rcnn#31]
git clone --recursive git@github.com:playerkk/face-py-faster-rcnn.git

Cloning into 'face-py-faster-rcnn'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Ir1d** [comment]
use `https://github.com/playerkk/face-py-faster-rcnn.git`
