### ISSUE TITLE
how to use the pre-trained model?

### ISSUE THREAD

**Issue by thuwangzhe** [playerkk/face-py-faster-rcnn#4]
Hi playerkk,
  I'm new to the face detection with faster-rcnn, here is my question:
  I have downloaded your pre-trained model "vgg16-faster-rcnn-iter-80000.caffemodel", but I don't know how to use it to test my own images. In the py-faster-rcnn, I can use the demo.py to test my images, but in your project, I don't know how to change it. Could you help me?
Thank you in advance.

**Comment by playerkk** [comment]
You can run 
python ./tools/run_face_detection_on_fddb.py --gpu=0
in the terminal. It will load the pre-trained model and run face detection on FDDB. You might need to take a look at the code.

**Comment by thuwangzhe** [comment]
oh, I know. I can change my images into the FDDB format, then test it. Thank you very much !

**Comment by playerkk** [comment]
Mostly likely the image reading failed. You might want to check the path of your input images.

**Comment by thuwangzhe** [comment]
I fixed it~ I build a wrong input path. Thank you !
