### ISSUE TITLE
Evaluation of accuracy

### ISSUE THREAD

**Issue by Usernamezhx** [playerkk/face-py-faster-rcnn#5]
hi playerkk
    I'm sorry to bother you again. after about two day training. i get the vgg16_faster_rcnn_iter_80000.caffemodel. and then I run  
**python ./tools/run_face_detection_on_fddb.py --gpu=0**
after that the screen display the number such:1 3.448 6.897 10.345 ..... and then I check the code: run_face_detection_on_fddb.py 
I find this : sys.stdout.write('%.3f ' % ((idx + 1) / len(image_names) * 100)). 
In addition to that. I want to know how do you evaluat the accuracy. after that : scores, boxes = im_detect(net, im) . we will get the scores, boxes .
But I was confused for the next code:
`      cls_ind = 1
      cls_boxes = boxes[:, 4*cls_ind:4*(cls_ind + 1)]
      cls_scores = scores[:, cls_ind]
      dets = np.hstack((cls_boxes,
                cls_scores[:, np.newaxis])).astype(np.float32)
      keep = nms(dets, NMS_THRESH)
      dets = dets[keep, :]

      keep = np.where(dets[:, 4] > CONF_THRESH)
      dets = dets[keep]

      # vis_detections(im, 'face', dets, CONF_THRESH)

      dets[:, 2] = dets[:, 2] - dets[:, 0] + 1
      dets[:, 3] = dets[:, 3] - dets[:, 1] + 1`
Thanks in advance. hope your reply.

**Comment by HaoXiedo** [comment]
hi @Usernamezhx,I'm a new guy,sorry to bother you .i was in the training model when there was a problem:
Path does not exist:data/WIDER/wider_face_train_annot.txt.
i would like to know WIDER directory in addition to WIDER_test,WIDER_train,WIDER_val,what else should i need.  
Hope to get your help .thanks a lot!

**Comment by Usernamezhx** [comment]
@HaoXiedo  
you should pay attention to the **Prepare training data** and the step 3 . Download the **file** and put it under the WIDER directory

**Comment by HaoXiedo** [comment]
@Usernamezhx thank you very much.I dowmload the file through your csdn blog,it started working!

**Comment by playerkk** [comment]
@Usernamezhx 
1. sys.stdout.write('%.3f ' % ((idx + 1) / len(image_names) * 100)) prints out the progress 
2. Since there are only two classes for face detection (background and face), we can simply get the score of being a face for a bounding box with cls_ind=1 (0 is for the score of being background).
3. You might find the evaluation script of FDDB helpful http://vis-www.cs.umass.edu/fddb/evaluation.tgz
