### ISSUE TITLE
Change in fetch_faster_rcnn_models.sh

### ISSUE THREAD

**Issue by aayushmudgal** [playerkk/face-py-faster-rcnn#7]
Change URL in /data/scripts/fetch_faster_rcnn_models.sh 

URL=http://www.cs.berkeley.edu/~rbg/faster-rcnn-data/$FILE

to

URL=https://github.com/rbgirshick/py-faster-rcnn/blob/master/data/scripts/fetch_faster_rcnn_models.sh

as the earlier website is now down

**Comment by playerkk** [comment]
The url has been updated. Thanks.
