### ISSUE TITLE
WIDER FACE training anno?

### ISSUE THREAD

**Issue by IssacCyj** [playerkk/face-py-faster-rcnn#8]
Cannot open http://jianghz.me/files/wider_face_train_annot.txt, how can I get it?

**Comment by playerkk** [comment]
You can find it at http://people.cs.umass.edu/~hzjiang/files/wider_face_train_annot.txt

**Comment by IssacCyj** [comment]
thanks a lot!

**Comment by xugangtongji** [comment]
but the new annot.txt is not the full of wider's annotations, it just stops at 9--Press_Conference/9_Press_Conference_Press_Conference_9_9.jpg
if run the ./experiments/scripts/faster_rcnn_end2end.sh 
it gets errors
`  File "/home/xugang/face-py-faster-rcnn/tools/../lib/datasets/face.py", line 114, in _load_image_set_index
    assert(image_ext == '.png' or image_ext == '.jpg' or image_ext == '.jpeg')
`

so how can we  get full annot.txt?

**Comment by xugangtongji** [comment]
@playerkk
