### ISSUE TITLE
datasets.inria in face.py?

### ISSUE THREAD

**Issue by IssacCyj** [playerkk/face-py-faster-rcnn#9]
Hi playerkk,

I find the following lines in face.py. However, I can't find how 'inria' functions. Is there anything that I missed?

Thank you in advance.
 
if __name__ == '__main__':
    d = datasets.inria('train', '')
    res = d.roidb

**Comment by playerkk** [comment]
Hi @IssacCyj , the face.py was greatly inspired by this one https://gist.github.com/ck196/dc165391a51d52a74315ab9a4534e40f, which introduced how to train the py-faster-rcnn on the Inria person dataset.

**Comment by IssacCyj** [comment]
Now I get it. Thank you anyway.
